version: "2.4"

services:
  php:
    image: php:7-fpm
    volumes:
      - ../:/var/www
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
